version: '3'
services:
  web:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    build: .
    container_name: manager-web
    ports:
      - "8001:8000"
    volumes:
      - "./app:/event_manager/app/"
      - "./requirements.txt:/event_manager/requirements.txt"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: manager-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}"]
      interval: 2s
      retries: 3
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
